const ROLES = {
    ADMIN: "admin",
    USER: "user"
}

const SCOPES = {
    DASHBOARD: "PAINEL",
    POS: "PDV",
    CUSTOMER_DISPLAY: "TELA DO CLIENTE", 
    KITCHEN_DISPLAY: "TELA DA COZINHA", 
    ORDER_STATUS_DISPLAY: "TELA DE STATUS DO PEDIDO", 
    ORDER_STATUS: "STATUS DO PEDIDO", 
    ORDERS: "PEDIDOS",
    KITCHEN: "COZINHA",
    RESERVATIONS: "RESERVAS",
    VIEW_RESERVATIONS: "VER RESERVAS", 
    MANAGE_RESERVATIONS: "GERENCIAR RESERVAS", 
    CUSTOMERS: "CLIENTES",
    VIEW_CUSTOMERS: "VER CLIENTES", 
    MANAGE_CUSTOMERS: "GERENCIAR CLIENTES", 
    INVOICES: "FATURAS",
    MEMBERSHIP: "ASSINATURA",
    INVENTORY: "ESTOQUE",
    VIEW_INVENTORY: "VER ESTOQUE", 
    MANAGE_INVENTORY: "GERENCIAR ESTOQUE", 
    SETTINGS: "CONFIGURAÇÕES",
    REPORTS: "RELATÓRIOS",
    FEEDBACK: "FEEDBACK",
}

exports.ROLES = ROLES;
exports.SCOPES = SCOPES;
